{"name": "Проверка наличия ошибки при неправильном логине или пароле", "status": "passed", "parameters": [{"name": "login", "value": "''"}, {"name": "password", "value": "''"}, {"name": "expected_status_code", "value": "400"}, {"name": "response_text", "value": "'{\"code\":400,\"message\":\"Недостаточно данных для входа\"}'"}], "start": 1730934778477, "stop": 1730934778523, "uuid": "b47ba155-c724-496a-90d8-512b4a5868ca", "historyId": "87a9bb6194832ee5f8265a16b8694432", "testCaseId": "95b67cc52f34af66d939aef0fd27906f", "fullName": "tests.courier.test_login_courier.TestLoginCourier#test_login_courier_false_fields", "labels": [{"name": "feature", "value": "Логин курьера"}, {"name": "parentSuite", "value": "tests.courier"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "mariamna-pc-kb2404"}, {"name": "thread", "value": "20070-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.courier.test_login_courier"}]}